const myArr = [1, 2, 3, 4, 5];
const myArr2 = new Array(2, 3, 4, 5);
console.log(myArr[1]);
myArr.push(6);
myArr.push(7);
myArr.pop(7);
console.log(myArr);
myArr.unshift(9);
myArr.unshift(8);
console.log(myArr);
console.log(myArr.includes(8));
console.log(myArr.indexOf(3));
const newArr = myArr.join();
console.log(myArr);
console.log(newArr);
console.log(typeof newArr);
